---
# relative path to file containing your GroupMe API key
api-key: groupme.key
# string to be used as command prompt
prompt: ~>
# avatar to be used as the avatar of any created bots
bot-avatar: https://i.groupme.com/1022x1024.jpeg.ef4c6f5678654593a1ea2ced390048eb
# startup greeting
greeting: gmcli by Quentin Young, version 1.0 -- type /help for help
